services:
  - type: web
    name: audit-backend
    env: java
    rootDir: backend
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/audit-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: audit-db
          property: connectionString
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: IQAC_APP_JWTSECRET
        generateValue: true

databases:
  - name: audit-db
    databaseName: iqac_audit_db
    user: iqac_user
