# Application name
spring.application.name=iqac-audit-backend

# Server port
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/iqac_audit_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# File Upload Configuration (Allow up to 50MB files)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Custom File Upload Path (Relative to project root)
iqac.upload.dir=uploads

# Spring Boot Mail configuration (Default dummy settings for local testing)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Security Configuration
iqac.app.jwtSecret=iqacAuditManagementSystemSecretKeyMustBeLongEnoughToMeetHMACRequirements
iqac.app.jwtExpirationMs=86400000
